[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://holiday-contact-app.netlify.app"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Credentials = "true"

